config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end

  # Defines the root path route ("/")
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_uniqueness_of :list, scope: :movie, message: "each movie can only be bookmarked once in a list"
  validates :comment, length: { minimum: 6}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
    @movies = Movie.all
  end

  def create
    @bookmark = Bookmark.new(bookmarks_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
    render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list

    if @bookmark.destroy
      redirect_to list_path(@list), notice: 'Le film a été supprimé avec succés.'
    else
      redirect_to list_path(@list), alert: 'Unable to delete the bookmark.'
    end
  end


  private

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    @bookmark = Bookmark.new
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list.id)
    else
      render :new, status: :unprocessable_entity
    end
  end



  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container pt-5">

<h1>Ajouter un film à <%= @list.name %></h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
<%= f.input :list_name, label: "Nom de la liste", input_html: { value: @list.name, readonly: true } %>
<%= f.association :movie, label: "Films" %>
<%= f.input :comment, label: "Commentaire" %>
<%= f.submit "Ajouter" %>
  <% end %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>

  <body>

  <%= render 'shared/navbar' %>
    <%= yield %>
  <%= render 'shared/footer' %>

  </body>
</html>

app/views/lists/index.html.erb
<%= render 'shared/carroussel_list' %>

<%# ---------- style pour que l'image garde la même taille ------------------- %>
<style>
  .custom-card-img {
    max-height: 350px;
    /* Ajustez la hauteur maximale souhaitée */
    object-fit: cover;
  }
</style>

<%# ---------- Bouton fixe en haut à droite ------------------- %>

<div class="container pt-5 position-relative">
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <%= link_to "Créer une nouvelle liste" , new_list_path, class: "btn btn-success me-md-2 mb-2 text-decoration-none text-white" %>
  </div>

  <%# --------------------------------------------- cards ------------------- %>
  <div class="row row-cols-1 row-cols-md-4 g-4">
    <% @lists.each do |list| %>
    <div class="col">
      <% image_url = ["https://fr.web.img6.acsta.net/pictures/22/07/22/11/32/1588141.jpg","https://fr.web.img6.acsta.net/pictures/23/07/28/14/17/5661948.jpg","https://toutelaculture.com/wp-content/uploads/2023/01/affiche-Babylone-680x924.webp", "https://fr.web.img5.acsta.net/pictures/23/08/01/13/52/4599315.jpg"].sample %>
      <%= link_to list_path(list), class: "text-decoration-none text-dark" do %>
      <div class="card h-100 d-flex flex-column">
        <img src="<%= image_url %>" class="card-img-top img-fluid custom-card-img" alt="...">
        <div class="card-body text-center d-flex flex-column">
          <h4 class="card-title flex-grow-1">
            <%= list.name %>
            <span class="small">(<%= list.movies.size %>)</span>
          </h4>
          <%= link_to new_list_bookmark_path(list.id), class: "btn btn-secondary mt-auto" do %>
          <i class="fas fa-plus"></i> Ajouter un film
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container pt-3">

<h1>Créer une nouvelle liste</h1>

<%= simple_form_for @list do |f| %>
    <%= f.input :name, label: "Nom de la liste"%>
    <%= f.submit "Créer" %>
  <% end %>


</div>

app/views/lists/show.html.erb
<%# -------------- BANNER ------------------------------------------------- %>

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%# -------------- Image en local ---------------------- %>
      <img src="<%= image_path('banner.png') %>" class="img-fluid w-100" alt="...">

      <div class="carousel-caption d-none d-md-block"
        style="position: absolute; top: 50%; transform: translateY(-50%);">
        <h1><%=@list.name%></h1>
        <p>K?edk,fe,fe, k,e,ozfofzek ofofeokfre</p>
      </div>
    </div>
  </div>
</div>


<%# -------------- Bouton ajouter un film---------------------- %>

<div class="container pt-5 position-relative">
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <%= link_to raw('<i class="fa-solid fa-arrow-rotate-left"></i> Retour'), :back, class: 'btn btn-secondary me-md-2' %>
    <%= link_to "Ajouter un film", new_list_bookmark_path(@list.id), class: "btn btn-primary" %>
  </div>
  <div class="container pt-5">


    <div class="row row-cols-1 row-cols-md-2 g-4">
      <%# -------------- Avoir accès à movie ---------------------- %>
      <% @list.movies.each do |movie| %>
      <%# -------------- Avoir accès à bookmark ---------------------- %>
      <% movie.bookmarks.each do |bookmark| %>
      <div class="col">
        <div class="card h-100 position-relative">
          <%# -------------- Bouton supprimer sur l'image ---------------------- %>
          <button class="btn btn-warning position-absolute top-0 end-0 m-2">
            <%= link_to "Supprimer", list_bookmark_path(@list, bookmark),
                        method: :delete,
                        data: { turbo_method: :delete, turbo_confirm: "Êtes-vous sûr de vouloir supprimer cet élément ?" } %>
          </button>
          <%# -------------- Image en local ---------------------- %>
          <img src="https://image.tmdb.org/t/p<%= movie.poster_url %>" class="card-img-top" alt="...">
          <div class="card-body">
            <%# -------------- Titre ---------------------- %>
            <h3 class="card-title"><%= movie.title %>
              <span class="small text-muted"> (<%= movie.rating.round(1) %><i class="fa-solid fa-star"
                  style="color: #f0e800;"></i>)</span>
            </h3>
            <%# --------------Texte ---------------------- %>
            <p class="card-text"><%= movie.overview %></p>
            <hr>
            <%# -------------- Commentaire + icone ---------------------- %>
            <i class="fa-solid fa-comment"></i> <%= bookmark.comment %>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
    <br>
  </div>

app/views/shared/_carroussel.html.erb
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
  <%#  --- Petit trait en bas du caroussel qui montre le nombre de slide -------- %>
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active"
      aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>

  <div class="carousel-inner">
    <%#  ------------------------------------ SLIDE 1 -------- %>
    <div class="carousel-item active">
      <img src="https://template.canva.com/EAENvp21inc/1/0/1600w-qt_TMRJF4m0.jpg" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <%#  ------------------------------------ SLIDE 2 -------- %>

    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <%#  ------------------------------------ SLIDE 3 -------- %>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>


  </div>


  <%#  -------------------- Boutton pour changer de slide ---------------------- %>

  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_carroussel_list.html.erb
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
  <%#  --- Petit trait en bas du caroussel qui montre le nombre de slide -------- %>


  <div class="carousel-inner">
    <%#  ------------------------------------ SLIDE 1 -------- %>
    <div class="carousel-item active">
      <img src="https://template.canva.com/EAENvp21inc/1/0/1600w-qt_TMRJF4m0.jpg" class="img-fluid" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h2>Mes listes de films</h2>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<br><br><br><br>
<footer class="text-center text-lg-start bg-body-tertiary text-muted w-100">
  <!-------------------------- Réseaux sociaux --------------------------->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Retrouvez-nous sur nos réseaux :</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset text-decoration-none">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset text-decoration-none">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset text-decoration-none">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset text-decoration-none">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset text-decoration-none">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset text-decoration-none">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>


  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <!-------------------------- JOUONS --------------------------->
            <i class="fa-solid fa-chess-board"></i> Jouons
          </h6>
          <p>
            Un site simple pour découvrir et louer des jeux de société autour de chez vous.
          </p>
        </div>

        <!-------------------------- NOS JEUX DU MOMENT --------------------------->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            Nos jeux du moment
          </h6>
          <p>
            <a href="#!" class="text-reset">Monopoly</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Catan</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Les petits chevaux canadiens</a>
          </p>
          <p>
            <a href="#!" class="text-reset">7 Wonders</a>
          </p>
        </div>

        <!-------------------------- LIENS UTILES --------------------------->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <h6 class="text-uppercase fw-bold mb-4">
            Liens utiles
          </h6>
          <p>
            <a href="#!" class="text-reset">Qui sommes-nous ?</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Nous contacter</a>
          </p>
          <p>
            <a href="#!" class="text-reset">FAQ</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Mentions Légales</a>
          </p>
        </div>

        <!-------------------------- CONTACT --------------------------->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> 12 rue du Palais Gallien, 33000, Bordeaux</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@jouons.fr
          </p>
          <p><i class="fas fa-phone me-3"></i> + 33 05 57 72 56 34</p>
        </div>
      </div>
    </div>
  </section>

  <!-------------------------- COPYRIGHT -------------------------------->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2023 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">jouons.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%#---------------- LOGO A GAUCHE ---------------------------------------- %>
    <a class="navbar-brand" href="/lists">
      <img
        src="https://img.freepik.com/vecteurs-premium/vecteur-logo-cinema-vecteur-film-rouleau-fond-blanc_472355-306.jpg?w=2000"
        alt="" width="45" height="45">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <%#---------------- HOME ---------------------------------------- %>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/lists">Accueil</a>
        </li>
        <%#---------------- Dropdown + list ---------------------------- %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            Voir toutes mes listes
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% List.all.each do |list| %>
            <li><a class="dropdown-item" href="/lists/<%= list.id %>"><%= list.name %></a></li>
            <% end %>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="#"><i class="fa-solid fa-plus"></i> Créer une nouvelle liste</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <%#---------------- Search ---------------------------- %>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
        <%#---------------- Ce que je veux ---------------------------------------- %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/lists">Accueil</a>
          </li>
        </ul>
      </form>
    </div>
  </div>
</nav>